# Generated by Django 3.1 on 2020-08-31 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_ratecar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratecar',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='cars.car'),
        ),
    ]
